config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :users, only: [:index, :create, :destroy]

  root 'matches#index'

  mount ActionCable.server => '/cable'
end

app/models/match.rb
class Match < ActiveRecord::Base
  # Created by this user
  belongs_to :user
  belongs_to :opponent, class_name: 'User', foreign_key: 'opponent_id'

  serialize :board, JSON

  before_create do
    self.turn = user.id
    self.board = '{"status": [
                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
                 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
                 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 2, 0, 2, 0, 2, 0, 2, 0, 2],
                 [2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
                 [0, 2, 0, 2, 0, 2, 0, 2, 0, 2],
                 [2, 0, 2, 0, 2, 0, 2, 0, 2, 0]
                ]}'
  end

  def owner?(user_id)
    self.user_id == user_id
  end

  def turn_of
    if turn == user.id
      user.username
    else
      opponent.username
    end
  end

  def swap_turns
    if turn == user.id
      self.turn = opponent.id
    else
      self.turn = user.id
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery with: :exception
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :ensure_authenticated_user
  end

  private

  def ensure_authenticated_user
    authenticate_user(cookies.signed[:user]) || redirect_to(users_path)
  end

  def authenticate_user(user_id)
    if (authenticated_user = User.find_by(id: user_id))
      cookies.signed[:user] ||= user_id
      @current_user = authenticated_user
    end
  end

  def unauthenticate_user
    ActionCable.server.disconnect(current_user: @current_user)
    @current_user = nil
    cookies.delete(:user)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  # GET /matches
  # GET /matches.json
  def index
    if params[:user].blank?
      @user = User.find(cookies.signed[:user])
    else
      @user = User.find(params[:user])
      cookies.signed[:user] = @user.id
    end

    @matches = Match.all.includes(:user)

    @your_matches = Match.where('user_id = :user_id or  ', @user.id)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @user = User.find(cookies.signed[:user])
    @match = Match.find(params[:id])
    @board = JSON.parse(@match.board).to_json
    
    @match.update_attribute(:opponent, @user) unless @user.matches.include?(@match)
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @user = User.find(cookies.signed[:user])
    @match = @user.matches.new(match_params)

    if @match.save
      # Send by broadcast the NEW MATCH!!
      ActionCable.server.broadcast('matches', match: @match, user: @user.username)
      redirect_to @match
    else
      render :new
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params[:match]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_authenticated_user

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def create
    authenticate_user(params[:user_id])
    redirect_to matches_path
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    unauthenticate_user

    redirect_to(users_path)
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>
<h3>Logged as: <%= @user.username %></h3>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="matches_list">
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to 'Play this match', match, class: "btn btn-success" %></td>
        <td>Room created by: <%= match.user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', matches_path, method: :post, class: "btn btn-primary" %>
<%= link_to 'Select another player', user_path(@user.id), class: "btn btn-default", method: :delete %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', matches_path %>
<h4>Logged as: <%= @user.username %></h4>

<!-- Match info -->
<span class="match_info" data-matchid="<%= @match.id %>" data-user-creator="<%= @match.user.username %>" data-user-opponent="<%= @match.opponent.try(:username)%>"></span>

<h3 id="players"></h3>

<div id="game" data-userid="<%= @user.id %>" data-username="<%= @user.username %>">
  <canvas id="board" width="0" height="0"></canvas>
  <div id="match_information">
    Turn of: <span id="turn_of" data-turnid="<%= @match.turn %>"><%= @match.turn_of %></span>
    </br>
  </div>

  <div id="game_actions">
    <button type="button" class="btn btn-danger" onclick="resetBoard()">Reset</button>
    <button type="button" class="btn btn-success" onclick="App.game_room.sendMove()">Send move</button>
  </div>
</div>

<div id="game_log"></div>

<%= javascript_tag do -%>
  initGame(<%= raw @board %>, <%= @match.owner?(@user.id) %>, <%= @user.id %>)
<% end -%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pick a username</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <p><%= link_to user.username, users_path(user_id: user.id), method: :post %></p>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>